efi =  0.040000
efi =  0.040000
Vida media (lambda)    --> Simulado: 9.6612e-05 (1.2582e-08)   Teorico: 9.6618e-05
Reproduciones (Lambda) --> Simulado: 1.0001e-04 (2.1040e-08)   Teorico: 1.0000e-04
k efectivo (keff)      --> Simulado: 9.6599e-01   Teorico: 9.6618e-01
Reactividad (rho)      --> Simulado: -3.5205e-02   Teorico: -3.5000e-02
Eficiencia detector    --> Simulado: 4.6265e-02   Teorico: 4.0000e-02
Tasa de fisiones       --> Simulado: 7.2998e+03   Teorico: 1.1735e+04
Tasa de detecciones    --> Simulado: 3.3773e+02   Teorico: 4.6941e+02
Tasa de absorciones    --> Simulado: 1.8397e+04   Teorico: 2.9571e+04
Cocientes	 T.fis: 1.6076 	 T.Det: 1.3899 	 T.Abs: 1.6074 
beta                   --> Teorico: 7.0000e-03
Fac. Diven (prompt)    --> Teórico: 0.7969
Alfa ret   --> Simulado: 8.3414e-03   Teorico: 8.3333e-03   Teorico_exacto: 8.3333e-03
Alfa inst  --> Simulado: 4.2199e+02   Teorico: 4.2000e+02   Teorico exacto: 4.2000e+02
efi =  0.040000
