Vida media (lambda)    --> Simulado: 0.8828   Teorico: 0.8839
Reproduciones (Lambda) --> Simulado: 1.3873   Teorico: 1.3893
k efectivo (keff)      --> Simulado: 0.6364   Teorico: 0.6362
Reactividad (rho)      --> Simulado: -0.5714  Teorico: -0.5718
Eficiencia detector    --> Simulado: 2.0020   Teorico: 2.0000
Tasa de fisiones       --> Simulado: 0.0006   Teorico: 0.6872
Tasa de detecciones    --> Simulado: 0.0011   Teorico: 1.3745
Tasa de absorciones    --> Simulado: 0.0022   Teorico: 2.7489
Cocientes	 T.fis: 1226.3651 	 T.Det: 1225.1537 	 T.Abs: 1225.5413 
beta                   --> Teorico: 0.0500
Alfa ret   --> Simulado: -0.0000   Teorico: -0.0000   Teorico_exacto: 0.0000
Alfa inst  --> Simulado: -0.4479   Teorico: -0.4476   Teorico exacto: 0.4476
